name: Daily Auto Commit

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at 00:00 UTC
  workflow_dispatch: # Allows manual triggers

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_PAT }}

    - name: Update file and commit
      run: |
        echo "Commit on $(date)" >> commit-tracker.txt
        git config --global user.name "nilayjain12"
        git config --global user.email "nilayjain12@github.com"
        git add commit-tracker.txt
        git commit -m "Daily auto-commit: $(date)"
        git push
