name: Update Contributions

on:
  schedule:
    - cron: '0 12 * * *'  # Runs every day at 12:00 UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  update_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update log file
        run: echo "$(date)" >> contributions.log

      - name: Commit and push changes
        run: |
          git config --global user.name "nilayjain12"
          git config --global user.email "nilayjain12@gmail.com"
          git add contributions.log
          git commit -m "Automated commit: $(date)"
          git push
